apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot
  namespace: kbot
spec:
  selector:
    matchLabels:
      app: kbot
  template:
    metadata:
      labels:
        app: kbot
    spec:
      containers:
        - name: kbot
          image: docker.io/devdp/cicd-test:v1.0-c8720f3-linux-amd64-stage
          imagePullPolicy: IfNotPresent