---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kbot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kbot
  filterTags:
    pattern: '(?P<ts>.*)-linux-amd64'
    extract: '$ts'
  policy:
    semver:
      range: '>=1.0.0'
